### ISSUE TITLE
Data - stores.csv/ oil.csv/holiday_events.csv

### ISSUE THREAD

**Issue by chitemerere** [rasmodev/Time-Series-Forecasting---ML-Regression-Project#1]
Thank you very much for this, where do I get the rest of the project data which is stated below:

stores.csv: 

oil.csv: 

holidays_events.csv:

**Comment by rasmodev** [comment]
Hello,

Allow me to look for the data source then I share the files with you.
Thanks.

**Comment by rasmodev** [comment]
Hello. I found the data. I have added a folder called data with all the CSV files. I have also updated the readme to include the links to the interactive PowerBI dashboard and the documentation of the project on Medium where you can understand everything that I did. Cheers!

**Comment by rasmodev** [comment]
I have added a folder called data with all the CSV files. Thanks.

**Comment by rasmodev** [comment]
I have also updated the readme to include the links to the interactive PowerBI dashboard, and the documentation of the project on medium where you can understand everything that I did. Cheers!
